# Generated by Django 3.0.4 on 2020-04-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_auto_20200405_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="main.Order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="estimated_daily_consumption",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("ML", "ml"), ("G", "gram"), ("PC", "piece")], max_length=2
            ),
        ),
    ]
