# Generated by Django 3.0.5 on 2020-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20200423_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=256, verbose_name="category name"),
        ),
    ]
