# Generated by Django 3.0.5 on 2020-04-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200425_1052"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category", unique_together={("name", "user")},
        ),
    ]
